name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: SSH into Server and Deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 159.69.34.52
        username: nikolai
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/portfolio/portfolio
          sudo git pull
          sudo npm run build
          sudo /root/.nvm/versions/node/v18.12.1/bin/pm2 restart portfolio
